### ISSUE TITLE
✏️ 작업: NextAuth를 이용한 일반 로그인 로직 구현

### ISSUE THREAD

**Issue by hvrain** [Codeit-FE08-Part4-Team7/wedo#25]
## 작업 예정 내용

- NextAuth를 사용해 일반 로그인 로직 구현

## 작업 세부 사항

- NextAuth 로직을 사용해 서버에서 받아온 accessToken을 session에 저장
- refreshToken을 사용하여 accessToken을 자동으로 획득하는 로직 구현
- 로그인 여부에 따른 redirect 로직 middleware를 통해 구현
- return-fetch를 사용한 api interceptor 구현

## 체크리스트

- [x] 해당 이슈의 타입에 알맞은 이슈의 Label을 등록하셨나요?
- [x] 해당 이슈의 작업 내용에 알맞은 Milestone을 등록하셨나요?
- [x] GitHub Projects에 연동하셨나요?
- [x] GitHub Projects에 시작일과 마감일을 작성 하셨나요?

## 기타

- package를 여러 개 추가하였습니다. (zod, next-auth, return-fetch, jwt-decode, bcrypt)
- 이미 다 만들어두고 이슈를 적습니다... (작업 전엔 세부 사항이 어떻게 될지 몰랐음, PR은 천천히 올릴 예정)
- 구현한 로직이 다소 생소해서 이해하기 어려울 수 있습니다. 그래서 설명을 댓글로 달아 올리겠습니다.

**Comment by hvrain** [comment]
client component에서 api 호출 방법

![image](https://github.com/user-attachments/assets/7ddcbf89-6a5e-4ccb-970c-451d872ec8be)

`fetchExtendedClient`를 불러와 사용하면 됩니다.
refetchInterval을 둔 이유는 fetch시에 `getSession`을 사용하는 부분이 있는데, 안에 session이 들어있지 않는 시간이 존재할 수 있기  때문입니다.

server component에서 api 호출 방법

![image](https://github.com/user-attachments/assets/04c25e4b-b064-49d6-8325-fafa1454a79d)

`fetchExtended`를 사용하면 서버 단에서 api를 호출할 수 있습니다.
현재 fetchExtended에는 refetch 기능이 없어서 호출 시 에러가 발생할 수 있습니다. 서버 단에서 useQuery를 사용할 수 있는지 모르겠는데, 확인해보고 되면 이슈를 따로 만들어 작성하겠습니다.

**Comment by hvrain** [comment]
### NextAuth 동작 원리

![image](https://github.com/user-attachments/assets/9ee155c4-51f3-46cf-9baa-c96d69277a5a)

signIn 함수를 서버 단에서 사용해야 **next-auth**를 사용할 수 있었기에, **server action**을 통해 구현하였습니다.
form을 작성하고, submit 버튼을 누르면 순서대로 동작하다가, signIn을 실행하게 됩니다.

![image](https://github.com/user-attachments/assets/7234d3ab-7e14-49a7-aef3-a1bf8d32f390)

signIn 함수를 실행하면 Credentials 안의 authorize 함수가 실행됩니다. 인증에 성공하였다면, user를 반환하고, jwt 함수를 실행합니다.

![image](https://github.com/user-attachments/assets/1e63ccc6-84d2-419a-a121-10f886d5e433)

jwt 함수는 **user가 제대로 반환되었는지 확인하고, accessToken이 만료되었는지 확인하는 과정**을 거칩니다.
jwt 함수가 종료되면, 이어서 session함수가 실행되고, session에서는 실제 사용될 session의 값을 조정하는 과정을 거칩니다. 현재는 **accessToken을 넘겨주어 api 호출할 때 참조할 수 있도록 해주었습니다.**

그 다음으로 `/api/auth/[...nextauth]/route.ts`를 거치며 마무리됩니다. (해당 route가 어떤 역할을 하는지 정확히 모르겠네요.)

![image](https://github.com/user-attachments/assets/3a945591-dd49-450f-81b6-7acbcd62f61a)

`middleware.ts`에는 인증 여부에 따라 리다이렉트가 이루어지도록 구현하였습니다.
middleware에 redirect를 구현하면 화면을 그리기 전에 페이지를 이동시킬 수 있습니다.
그래서 **서버 컴포넌트를 사용한다면 보안적인 문제를 해결하고, 클라이언트 컴포넌트를 사용한다면 성능 문제를 개선하는 효과를 가져옵니다.**

**Comment by leehj322** [comment]
강우님 갑자기 생각난 내용인데 지금 코드상에서 토큰을 직접 인코딩해서 만료가 되었는지를 체크하는 것 같은데
만약에 저희가 체크했을때는 괜찮았는데 관련된 네트워크 요청을 보냈을때 갑자기 만료가 되는 경우도 생길 수 있을 것 같은데 어떤가요?
