### ISSUE TITLE
🔊 논의: OAuth에 대한 요구사항을 만족시킬 수 없는 문제

### ISSUE THREAD

**Issue by hvrain** [Codeit-FE08-Part4-Team7/wedo#45]
## 주제

- OAuth에 대한 요구사항을 만족시킬 수 없는 문제

## 상세 내용

- 요구사항에서는 OAuth시 회원가입이 해당 서비스에 대한 회원가입이 되어있지 않으면, "/oauth/signup/{google/kakao}"로 redirect되도록 되어있음
- 하지만 Swagger API 상에선 사용자가 OAuth로 로그인을 시도할 때, 회원가입 되어 있는지, 아닌지 확인할 방법이 없음
- 왜냐하면 Swagger에서는 "/auth/signIn/{provider}"라는 경로로 로그인과 회원가입 모두 확인하게 되고, reponse로 오는 데이터도 회원가입인지 로그인인지 알려주지 않음

## 주로 논의 하고 싶은 내용

생각나는 대안 혹은 해결책
1. "/auth/signin/{provider}"의 응답으로 첫 로그인인지 아닌지 판단할 수 있는 값을 보내주게 매니저님께 수정 요청해본다.
 - 그러면, 보내준 값을 통해 유저가 첫 로그인이라면 "/oauth/signup/{google/kakao}"로 redirect 시켜 유저 정보를 수정하게 할 수 있을 것 같다.

2. OAuth 로그인 시 첫 로그인인지 아닌지 신경쓰지 않는 법
 - 요구사항의 "oauth/signup/{google|kakao}"를 구현하지 않는 방법이다.
 - 이러면 유저는 첫 로그인이더라도 유저 정보를 변경하기 위해 계정설정 페이지로 이동해야한다. (크게 중요하진 않을듯??)
 

## 참고자료

- [요구사항](https://codeit.notion.site/Coworkers-1146fd228e8d810bae25e4e6407af47f)

**Comment by leehj322** [comment]
2번으로 해서 하는게 좋을 것 같습니다! 사실 첫 로그인인지 아닌지 판단할 수 있는 방법이 어떤게 있을지 잘 떠오르지 않네요.. 혹시 1번으로 하는 경우에 어떻게 판단할 수 있을까요??
