### ISSUE TITLE
✏️ 작업: husky 적용

### ISSUE THREAD

**Issue by hvrain** [Codeit-FE08-Part4-Team7/wedo#9]
## 작업 예정 내용

- husky 적용을 통해 모든 commit에 대해 코드 컨벤션을 지키도록 강제하고 싶습니다.

## 작업 세부 사항

- 여러분들이 사용하실 땐 `npm i` 명령어를 터미널에 치시기만 하면 끝나도록 세팅해놓겠습니다.

husky가 잘 적용되었다면, commit을 할 때, 다음과 같은 내용이 터미널에 보입니다.

![image](https://github.com/user-attachments/assets/c084bc47-5be8-45a1-9a86-3fbb35931923)

만약 lint error 가 발생하면 commit이 생성되지 않고, lint 규칙을 모두 만족했을 때 그제서야 commit을 생성하게 됩니다.

* 한가지 주의사항

git commit을 했을 때, 규칙을 잘 지켜 커밋을 생성할 때, staged area에 있는 파일 중 일부가 누락되는 경우가 발생합니다.

그럴 땐, 
`git add .`
`git commit --amend`
명령어를 순서대로 입력하여, commit 기록을 관리하시면 됩니다.

## 체크리스트

- [x] 해당 이슈의 타입에 알맞은 이슈의 Label을 등록하셨나요?
- [x] 해당 이슈의 작업 내용에 알맞은 Milestone을 등록하셨나요?
- [x] GitHub Projects에 연동하셨나요?
- [x] GitHub Projects에 시작일과 마감일을 작성 하셨나요?

**Comment by leehj322** [comment]
강우님! 말씀해주신 부분에서 약간 이해가 안되는 부분이 있어서 질문 드립니다!

> git commit을 했을 때, 규칙을 잘 지켜 커밋을 생성할 때, staged area에 있는 파일 중 일부가 누락되는 경우가 발생합니다.
> 그럴 땐,
> git add .
> git commit --amend
> 명령어를 순서대로 입력하여, commit 기록을 관리하시면 됩니다.

이거는 husky 자체적인 오류일까요?
저는 모든 파일을 한번에 커밋하는 스타일이 아니라서 몇몇 파일을 나눠서 커밋하는 경우도 있는데 그렇게 해도 문제 없을까요?

**Comment by hvrain** [comment]
1. husky 자체적인 오류는 아닌 것 같아요. 그런데, 해결 방법을 아직 찾지 못해서 그렇습니다
2. staged area에 올라간 파일 (git add 한 파일들)만 lint 검사를 하고 commit을 만들거에요. 그래서 문제 없을 듯 합니다.
